//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 08:20:01 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.parlament.gov.rs/korisnik", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.skupstina.model.users;
